services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - joker_net

  backend:
    container_name: backend
    build: .
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - mongo
    networks:
      - joker_net
    expose:
      - "8080"

  mongo:
    image: mongo:4.2.5
    volumes:
      - mongo-data:/data/db
    networks:
      - joker_net

volumes:
  mongo-data:

networks:
  joker_net:
    driver: bridge
