#version: "3.9" remove this should still work

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app         
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.5
    ports:
      - "27017:27017"   #this part must be removed before deploying
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
