services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.5
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
