services:
  backend:
    build: .
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.5
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
